'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Memória.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _49ers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_49ers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Abacate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Abacate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Abacaxi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Abacaxi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ABC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ABC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ajax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ajax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alemanha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alemanha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property América() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("América", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arábia_Saudita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arábia_Saudita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Argentina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Argentina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Arsenal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arsenal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Atlético_de_Bilbao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atlético_de_Bilbao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Atlético_de_Madri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atlético_de_Madri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Atlético_GO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atlético_GO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Atlético_MG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atlético_MG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Atlético_PR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Atlético_PR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Austrália() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Austrália", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Avaí() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Avaí", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bacon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bacon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bahia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bahia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Banana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Banana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Barcelona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Barcelona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Batata_Frita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Batata_Frita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bayern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bayern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bears() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bears", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Benfica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Benfica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bengals() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bengals", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bills() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bills", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bolo_de_Aniversário() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bolo_de_Aniversário", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Borussia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Borussia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Botafogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Botafogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bragantino() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bragantino", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Icon semelhante a (Ícone).
        '''</summary>
        Friend ReadOnly Property Brain() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Brain", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Brasil() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Brasil", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Broncos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Broncos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Browns() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Browns", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Buccaneers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buccaneers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cachorro_Quente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cachorro_Quente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cadeado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cadeado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Café() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Café", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Caixa_de_Correio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Caixa_de_Correio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Câmera_de_Vídeo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Câmera_de_Vídeo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Câmera_Fotográfica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Câmera_Fotográfica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Canadá() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Canadá", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Caneta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Caneta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cardinals() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cardinals", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Carne() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carne", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CBF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CBF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ceará() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ceará", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cenoura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cenoura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cereja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cereja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cerveja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cerveja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chapecoense() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chapecoense", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chargers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chargers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chave_de_Boca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chave_de_Boca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chelsea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chelsea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chiefs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chiefs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chocolate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocolate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chuveiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chuveiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cigarro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cigarro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Clipe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Clipe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Coco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Colômbia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Colômbia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Colts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Colts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Comidas_e_Bebidas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comidas_e_Bebidas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Coquetel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coquetel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Coréia_do_Sul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coréia_do_Sul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Corinthians() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Corinthians", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Coritiba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Coritiba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cowboys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cowboys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Croácia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Croácia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cruzeiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cruzeiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CSKA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CSKA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dinheiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dinheiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dolphins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dolphins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Eagles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Eagles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Espaguete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Espaguete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Espanha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Espanha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Estados_Unidos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Estados_Unidos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Estrela_Vermelha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Estrela_Vermelha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Falcons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Falcons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Finlândia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Finlândia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Flamengo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flamengo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fluminense() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fluminense", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fone_de_Ouvido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fone_de_Ouvido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fortaleza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fortaleza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property França() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("França", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frango() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frango", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Giants() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Giants", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grécia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grécia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Grêmio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grêmio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Guitarra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guitarra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Holanda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Holanda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Inter_de_Milão() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inter_de_Milão", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Internacional() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Internacional", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Irlanda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Irlanda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Israel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Israel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Itália() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Itália", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jaguars() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jaguars", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Japão() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Japão", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Jets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Jets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Juventus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Juventus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Kiwi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Kiwi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lâmpada() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lâmpada", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lanterna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lanterna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lápis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lápis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lazio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lazio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Liverpool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Liverpool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Livro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Livro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lokomotiv_Moscow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lokomotiv_Moscow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lupa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lupa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Lyon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lyon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Maçã() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maçã", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Manchester_City() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Manchester_City", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Manchester_United() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Manchester_United", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Marrocos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Marrocos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Martelo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Martelo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Melancia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Melancia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mexerica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mexerica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property México() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("México", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Microfone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Microfone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Microscópio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Microscópio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Milan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Milan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Morango() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Morango", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Mouse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mouse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Napoli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Napoli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Náutico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Náutico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NFL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NFL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nigéria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nigéria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Noruega() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Noruega", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Nota_Musical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nota_Musical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Notebook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Notebook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Objetos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Objetos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ovo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ovo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Packers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Packers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Palmeiras() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Palmeiras", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Panthers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Panthers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pão() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pão", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Parafuso_e_Porca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Parafuso_e_Porca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paraná() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paraná", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patriots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patriots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paysandu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paysandu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pipoca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pipoca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pizza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pizza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Polônia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Polônia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Porto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Porto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Portugal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Portugal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PSG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PSG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PSV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PSV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Queijo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Queijo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rádio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rádio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Raiders() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Raiders", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rams() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rams", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ravens() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ravens", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Real_Madrid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Real_Madrid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Real_Sociedad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Real_Sociedad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Reino_Unido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reino_Unido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property República_Tcheca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("República_Tcheca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Roma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Roma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Romênia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Romênia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rússia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rússia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Saints() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Saints", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sanduíche() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sanduíche", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Santa_Cruz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Santa_Cruz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Santos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Santos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property São_Paulo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("São_Paulo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Seahawks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seahawks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Shakhtar_Donetsk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shakhtar_Donetsk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sorvete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sorvete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sporting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sporting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Steelers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Steelers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Suécia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Suécia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tachinha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tachinha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Telefone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Telefone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Telescópio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Telescópio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Televisão() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Televisão", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Terra() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Terra", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tesoura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tesoura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Texans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Texans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Titans() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Titans", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tottenham() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tottenham", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Troféu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Troféu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tunísia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tunísia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tupi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tupi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UEFA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UEFA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uísque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uísque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property URT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("URT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uruguai() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uruguai", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Uva() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uva", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Valencia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Valencia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vasco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vasco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vela() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vela", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vikings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vikings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Viktoria_Plzen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Viktoria_Plzen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Villa_Nova() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Villa_Nova", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vinho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vinho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Vitória() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vitória", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Washington() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Washington", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
